### ISSUE TITLE
Searching causes error

### ISSUE THREAD

**Issue by larseggert** [ietf-authors/authors.ietf.org#21]
<img width="940" alt="Screen Shot 2022-04-08 at 9 57 12" src="https://user-images.githubusercontent.com/200328/162381254-c2840d47-a43b-496e-a9d8-ef8159f9709e.png">

**Comment by JayDaley** [comment]
i will escalate this.

**Comment by larseggert** [comment]
#14 seems related (this may be a duplicate)

**Comment by NGPixel** [comment]
Was the database migrated recently?

Only thing I can think of is that the `pg_trgm` extension is not enabled in postgres. It gets created when enabling Postgres search the first time.

Basic search works, so the issue is within the postgres search module and rebuilding the index doesn't solve it. The only difference between `init()` and `rebuild()` is the creation of the `pg_trgm` extension.

So running `CREATE EXTENSION IF NOT EXISTS pg_trgm` on the database could be worth a try.

**Comment by NGPixel** [comment]
pg_trgm extension has been installed on the server by Glen and I've run an index rebuild. Search results now appear correctly.
